// AppDelegate.m — Boots the Mob BEAM on a background thread and presents
// a SwiftUI root view via UIHostingController (created by MobUIFactory).

#import <UIKit/UIKit.h>
#import <pthread.h>
#include "mob_beam.h"
#import "MobApp-Swift.h"  // generated by swiftc; exposes MobUIFactory

// Declared in mob_nif — delivers {:push_token, :ios, token} to the registered screen process.
extern void mob_send_push_token(const char* hex_token);

// Code-generated by MobDev.Plugin.IOSBootstrap at build time — registers each
// activated plugin's SwiftUI view with MobNativeViewRegistry.shared. Defined
// via Swift's @_cdecl in the generated file so it's a plain C symbol; safe to
// call before mob_init_ui() even when no plugins are activated (the function
// body is just empty in that case).
extern void mob_register_plugins(void);

// Exported by mob_nif: tells the BEAM a window scene has connected so screens
// can re-read safe-area insets they may have taken before one existed.
extern void mob_notify_window_connected(void);

// Exported by mob_nif: the orientation mask set by Mob.Device.lock_orientation/1
// (UIInterfaceOrientationMaskAll when unlocked).
extern UIInterfaceOrientationMask mob_locked_orientation_mask(void);

static void* beam_thread(void* arg) {
    mob_start_beam((const char*)arg);
    return NULL;
}

// Boot the runtime exactly once per process, from whichever entry point runs
// first.
//
// Both callers matter. -application:didFinishLaunchingWithOptions: runs on
// every launch, including ones that connect no window scene: a background
// launch, and an iOS 15+ prewarmed launch, which for a scene-based app calls
// this method and creates no scene. scene:willConnectToSession: covers a scene
// reconnecting into a process that somehow has not booted.
//
// Boot order is deliberately NOT load-bearing. It used to be: Mob.Screen reads
// the safe-area insets during init, and mob's nif_safe_area could only answer
// zeros before a window existed, which Mob.Screen then cached for the screen's
// lifetime — a root screen laid out under the notch. Gating this on
// applicationState looked like the fix and is not, because that state means
// "background launch OR prewarm" and there is no reliable way to tell them
// apart here. mob's nif_safe_area now reports :no_window distinctly and the
// screen refuses to cache it, so any boot order is safe.
//
// The guard lives here, in the shared function, rather than in either caller: a
// dispatch_once_t scoped to one method cannot see that the other already
// booted, and a second erl_start in the same process is fatal.
static void mob_boot_runtime(void) {
    static dispatch_once_t mob_boot_once;
    dispatch_once(&mob_boot_once, ^{
        // Must run before mob_init_ui() so the registry has every plugin view
        // factory in place by the time the BEAM mounts its first screen.
        mob_register_plugins();

        mob_init_ui();

        extern const char* mob_app_module(void);
        pthread_t t;
        pthread_create(&t, NULL, beam_thread, (void*)mob_app_module());
        pthread_detach(t);
    });
}

@interface AppDelegate : UIResponder <UIApplicationDelegate>
@end

@implementation AppDelegate

// This method runs on every launch, including ones that never connect a window
// scene, so it is the only place that can guarantee the runtime starts at all.
- (BOOL)application:(UIApplication*)app
    didFinishLaunchingWithOptions:(NSDictionary*)opts {
    mob_boot_runtime();
    return YES;
}

// Holds an orientation lock. UIKit consults this window-level method in
// preference to the root view controller's -supportedInterfaceOrientations, so
// the rotation Mob.Device.lock_orientation/1 requests via requestGeometryUpdate
// actually sticks (and unlock_orientation/0 returns ...MaskAll = follow sensor).
- (UIInterfaceOrientationMask)application:(UIApplication*)app
    supportedInterfaceOrientationsForWindow:(UIWindow*)window {
    return mob_locked_orientation_mask();
}

- (void)application:(UIApplication*)app
    didRegisterForRemoteNotificationsWithDeviceToken:(NSData*)deviceToken {
    // Convert token bytes to hex string and deliver to Elixir via NIF.
    NSMutableString* hex = [NSMutableString stringWithCapacity:deviceToken.length * 2];
    const unsigned char* bytes = (const unsigned char*)deviceToken.bytes;
    for (NSUInteger i = 0; i < deviceToken.length; i++) {
        [hex appendFormat:@"%02x", bytes[i]];
    }
    mob_send_push_token([hex UTF8String]);
}

- (void)application:(UIApplication*)app
    didFailToRegisterForRemoteNotificationsWithError:(NSError*)error {
    NSLog(@"[Mob] Failed to register for remote notifications: %@", error);
}

@end

// SceneDelegate — Xcode 27 requires scene-based app startup, so window creation
// lives here rather than in AppDelegate.didFinishLaunchingWithOptions:. The
// BEAM boot happens here too on an ordinary launch, after the window exists;
// a background launch connects no scene and boots from the AppDelegate instead.
@interface SceneDelegate : UIResponder <UIWindowSceneDelegate>
@property (strong, nonatomic) UIWindow *window;
@end

@implementation SceneDelegate

- (void)scene:(UIScene*)scene
    willConnectToSession:(UISceneSession*)session
    options:(UISceneConnectionOptions*)connectionOptions {
    if (![scene isKindOfClass:[UIWindowScene class]]) {
        return;
    }

    self.window = [[UIWindow alloc] initWithWindowScene:(UIWindowScene*)scene];
    self.window.rootViewController = [MobUIFactory makeRootViewController];
    [self.window makeKeyAndVisible];

    // Tell the BEAM the window exists. Safe-area insets are read from it, and a
    // screen that painted before this point is holding placeholder zeros with
    // nothing to correct them — nothing else repaints when a scene connects. A
    // no-op when the runtime is not up yet, in which case the boot below reads
    // the real insets anyway.
    mob_notify_window_connected();

    // The ordinary path, and deliberately after makeKeyAndVisible above: the
    // boot path reads window state. willConnectToSession: can also fire more
    // than once per process — iOS may disconnect the scene under memory
    // pressure and reconnect it without relaunching — so the window is rebuilt
    // every time while the boot below is a no-op after the first call,
    // whichever entry point made it.
    mob_boot_runtime();
}

@end

int main(int argc, char* argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, @"AppDelegate");
    }
}
